# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyqt5 pyperclip
        
    - name: Testing Syntax
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    #- name: Test with pytest
      #run: |
        #pytest
        
    - name: Build App from Python Script (Nuitka)
      uses: Nuitka/Nuitka-Action@v0.4
      with:
          script-name: File-Find.py
          macos-create-app-bundle: true
          disable-console: true
          output-dir: ./
          
  
    - name: Zip .app
      run: zip -r File-Find.zip File-Find.app
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: File-Find
          path: ./File-Find.zip      
          
          
      

