# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: File Find

on:
  push:
    paths-ignore: ["**/**.md", "**/**.dox2", "**/**.dox", "**/**.dox.in", "**/LICENSE.txt", "/.github/ISSUE_TEMPLATE/**", "INSTALL", "CHANGELOG.txt", ".editorconfig", ".gitignore", ".gitatributes"]
  pull_request:
    paths-ignore: ["**/**.md", "**/**.dox2", "**/**.dox", "**/**.dox.in", "**/LICENSE.txt", "/.github/ISSUE_TEMPLATE/**", "INSTALL", "CHANGELOG.txt", ".editorconfig", ".gitignore", ".gitatributes"]

permissions:
  contents: read

jobs:
  check-syntax:
    name: "Checking Syntax"
    runs-on: macos-latest
    
    steps:
    
    - name: Setup
      uses: actions/checkout@v3
    
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flake8
          # flake 8 plugins
          pip install flake8-qt-tr flake8-alfred flake8-debugger flake8-use-fstring pep8-naming flake8-eradicate flake8-bugbear flake8-builtins
          pip install -r requirements.txt
          
    - name: Testing Syntax
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


  build-macos-arm:
    name: "Building macOS ARM (Apple Silicon) App"
    runs-on: macos-14

    steps:
    - name: Setup
      uses: actions/checkout@v3
      
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        # Installing python dependencies
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        # Install create-dmg 
        brew install create-dmg
    
    - name: Build .app with nuitka and creating dmg
      run: |
        # Building File Find
        # Build arch is depending on system arch
        python3 build.py
        
    - name: Zip .app
      run: |
        cd dist
        zip -r "File Find.app.zip" "File Find.app"
        
    # Upload app
    - name: Upload File Find.app
      uses: actions/upload-artifact@v2
      with:
          if-no-files-found: error
          name: File Find.app.zip
          path: dist/File Find.app.zip
          
    # Upload dmg
    - name: Upload File Find.dmg
      uses: actions/upload-artifact@v2
      with:
          if-no-files-found: warn
          name: File Find.dmg
          path: dist/File Find.dmg  

  



  build-macos-intel:
    name: "Building macOS Intel App"
    runs-on: macos-12

    steps:
    - name: Setup
      uses: actions/checkout@v3
      
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        # Installing python dependencies
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        # Install create-dmg 
        brew install create-dmg
    
    - name: Build .app with nuitka and creating dmg
      run: |
        # Building File Find
        # Build arch is depending on system arch
        python3 build.py
        
    - name: Zip .app
      run: |
        cd dist
        zip -r "File Find.app.zip" "File Find.app"
        
    # Upload app
    - name: Upload File Find.app
      uses: actions/upload-artifact@v2
      with:
          if-no-files-found: error
          name: File Find.app.zip
          path: dist/File Find.app.zip
          
    # Upload dmg
    - name: Upload File Find.dmg
      uses: actions/upload-artifact@v2
      with:
          if-no-files-found: warn
          name: File Find.dmg
          path: dist/File Find.dmg  

  build-windows:
    name: "Building Windows exe"
    runs-on: windows-latest

    steps:
    - name: Setup
      uses: actions/checkout@v3
      
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        # Installing python dependencies
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build .exe with nuitka
      run: |
        # Building File Find
        python3 build.py
            
    # Upload executable
    - name: Upload File Find.exe
      uses: actions/upload-artifact@v2
      with:
          if-no-files-found: error
          name: File Find.exe
          path: dist\File Find.exe

  build-linux:
    name: "Building Linux App"
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: actions/checkout@v3
      
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        # Installing python dependencies
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build app with nuitka
      run: |
        # Building File Find
        python3 build.py
  
        
    # Upload app
    - name: Upload File Find.app
      uses: actions/upload-artifact@v2
      with:
          if-no-files-found: error
          name: File Find.bin
          path: dist/File Find.bin
          


